project_id = "kzaeahjeqlihmxrfhjqd"

[functions.extract-audio]
verify_jwt = false

[functions.jamendo-search]
verify_jwt = false

[functions.yt-music-search]
verify_jwt = false

[functions.gemma-chat]
verify_jwt = false

[functions.music-indexer]
verify_jwt = false

[functions.verify-registered-user]
verify_jwt = false

[functions.send-system-push]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false
